import type { AITool, ToolCall } from "./tools.js";
import type { JSONSchema, ResponseFormat } from "./schema.js";

/**
 * Roles supported across all AI models
 */
export type ChatRole = "system" | "user" | "assistant" | "tool";

/**
 * Finish reasons returned by providers
 */
export type FinishReason =
  | "stop"
  | "length"
  | "tool_calls"
  | "content_filter"
  | "error"
  | "other";

/**
 * Text part in a multimodal message
 */
export interface TextContentPart {
  type: "text";
  text: string;
}

/**
 * Image part in a multimodal message
 */
export interface ImageContentPart {
  type: "image";
  /**
   * Base64 string, data URL (e.g. data:image/png;base64,...), or remote HTTP/HTTPS URL
   */
  image: string | Uint8Array | ArrayBuffer;
  mimeType?: string;
  detail?: "auto" | "low" | "high";
}

/**
 * Audio part in a multimodal message
 */
export interface AudioContentPart {
  type: "audio";
  /**
   * Base64 or raw binary audio data
   */
  data: string | Uint8Array;
  mimeType: string;
}

/**
 * Document or PDF part in a multimodal message
 */
export interface FileContentPart {
  type: "file";
  /**
   * Base64 data or URL
   */
  data: string | Uint8Array;
  mimeType: string;
  filename?: string;
}

/**
 * Union of all multimodal message content parts
 */
export type ChatContentPart =
  | TextContentPart
  | ImageContentPart
  | AudioContentPart
  | FileContentPart;

/**
 * Unified Chat Message
 */
export interface ChatMessage {
  role: ChatRole;
  content: string | ChatContentPart[];
  name?: string;
  toolCallId?: string;
  toolCalls?: ToolCall[];
}

/**
 * Token usage statistics
 */
export interface UsageInfo {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
  reasoningTokens?: number;
  cachedTokens?: number;
  estimatedCostUsd?: number;
}

/**
 * Chat execution options
 */
export interface ChatOptions {
  /**
   * Direct text prompt or list of multi-turn chat messages
   */
  prompt?: string;
  messages?: ChatMessage[];

  /**
   * Target model identifier (e.g. 'gemini-2.0-flash', 'gpt-4o', 'claude-3-5-sonnet')
   */
  model?: string;

  /**
   * Sampling temperature between 0 and 2
   */
  temperature?: number;

  /**
   * Maximum tokens to generate
   */
  maxTokens?: number;

  /**
   * Nucleus sampling threshold
   */
  topP?: number;

  /**
   * Top-k sampling (where supported)
   */
  topK?: number;

  /**
   * Frequency penalty (-2.0 to 2.0)
   */
  frequencyPenalty?: number;

  /**
   * Presence penalty (-2.0 to 2.0)
   */
  presencePenalty?: number;

  /**
   * Sequences where the model will stop generating
   */
  stopSequences?: string[];

  /**
   * Tools / Functions available for the model to invoke
   */
  tools?: AITool[];

  /**
   * Controls tool calling behavior
   */
  toolChoice?: "auto" | "none" | "required" | { type: "tool"; name: string };

  /**
   * Maximum recursive tool execution turns (default: 5)
   */
  maxToolSteps?: number;

  /**
   * Structured response format (JSON or Schema)
   */
  responseFormat?: ResponseFormat;

  /**
   * Optional system instruction
   */
  systemInstruction?: string;

  /**
   * Request timeout in milliseconds
   */
  timeoutMs?: number;

  /**
   * Maximum retry attempts on retryable errors (default: 3)
   */
  retries?: number;

  /**
   * Abort signal for request cancellation
   */
  abortSignal?: AbortSignal;

  /**
   * Additional custom headers for the provider
   */
  headers?: Record<string, string>;

  /**
   * Provider-specific raw options
   */
  extra?: Record<string, unknown>;
}

/**
 * Standard AI Response returned by all providers
 */
export interface AIResponse {
  /**
   * Text output generated by the model
   */
  text: string;

  /**
   * Thinking / reasoning tokens for reasoning models (e.g. DeepSeek-R1, o1, o3-mini)
   */
  reasoningContent?: string;

  /**
   * Tool calls requested by the model
   */
  toolCalls?: ToolCall[];

  /**
   * Finish reason
   */
  finishReason?: FinishReason;

  /**
   * Token usage metadata
   */
  usage?: UsageInfo;

  /**
   * Provider that processed the request
   */
  provider: string;

  /**
   * Model that processed the request
   */
  model: string;

  /**
   * Raw response payload from the underlying provider
   */
  rawResponse?: unknown;
}

/**
 * Stream Chunk emitted during real-time streaming
 */
export interface AIChunk {
  /**
   * Full text accumulated so far
   */
  text: string;

  /**
   * Incremental text delta for this specific chunk
   */
  delta: string;

  /**
   * Thinking / reasoning delta for reasoning models
   */
  reasoningDelta?: string;

  /**
   * Tool call chunks received so far
   */
  toolCallChunks?: Array<{
    id?: string;
    name?: string;
    argumentsDelta?: string;
  }>;

  /**
   * Finish reason if stream is completed
   */
  finishReason?: FinishReason;

  /**
   * Token usage if provided in final chunk
   */
  usage?: UsageInfo;

  /**
   * Raw chunk object from provider
   */
  rawChunk?: unknown;
}
